spring:
  application:
    name: ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID_CLIENT}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

api:
  jwt:
    secret: ${SPRING_SECRET_JWT}
    expiration-ms: 86400000
  oauth2:
    redirect-uri: http://localhost:3000/login/callback



server:
  error:
    include-stacktrace: never

