networks:
  ecommerce_network:

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ecommerce_network
    ports:
      - "8080:8080"
    environment:
#      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy # Espera o db estar saudável

  db:
    image: mysql:8.0.43-debian
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: [
           '--default-authentication-plugin=mysql_native_password',
           '--lower-case-table-names=1'
             ]
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d

    healthcheck: # Adiciona um healthcheck ao serviço do banco de dados
      test: [ "CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "ecommerce_db" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - ecommerce_network

